spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    proporties:
      hibernate:
        format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 6060

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka #endereço do servidor eureka - service discovery

  instance:
    prefer-ip-address: true